# Generated by Django 5.2 on 2025-04-05 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armazem', '0002_estoque'),
    ]

    operations = [
        migrations.AddField(
            model_name='estoque',
            name='quantidade',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Quantidade em Kg', max_digits=10, verbose_name='Quantidade em (Kg)'),
        ),
    ]
