# Generated by Django 5.2 on 2025-04-06 02:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armazem', '0005_alter_estoque_produto'),
        ('pessoas', '0002_rename_pessoa_afiliado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estoque',
            name='quantidade',
            field=models.DecimalField(decimal_places=3, default=0.0, help_text='Quantidade em Kg', max_digits=10, verbose_name='Quantidade'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='preco',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Preço por Kg', max_digits=10, verbose_name='Preço'),
        ),
        migrations.CreateModel(
            name='HistoricoEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada'), ('saida', 'Saída')], default='entrada', max_length=10)),
                ('peso', models.DecimalField(decimal_places=3, default=0.0, help_text='Peso em Kg', max_digits=10, verbose_name='Peso')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('afiliado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pessoas.afiliado')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='armazem.produto')),
            ],
            options={
                'verbose_name': 'Histórico de Estoque',
                'verbose_name_plural': 'Histórico de Estoques',
            },
        ),
        migrations.CreateModel(
            name='EstoqueIndividual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=3, default=0.0, help_text='Quantidade em Kg', max_digits=10, verbose_name='Quantidade')),
                ('afiliado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pessoas.afiliado')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='armazem.produto', unique=True)),
            ],
            options={
                'verbose_name': 'Estoque Individual',
                'verbose_name_plural': 'Estoques Individuais',
                'unique_together': {('produto', 'afiliado')},
            },
        ),
    ]
