# Generated by Django 5.2 on 2025-04-06 02:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armazem', '0006_alter_estoque_quantidade_alter_produto_preco_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estoqueindividual',
            name='produto',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='armazem.produto'),
        ),
    ]
