# Generated by Django 5.2 on 2025-04-06 02:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armazem', '0007_alter_estoqueindividual_produto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estoqueindividual',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='armazem.produto'),
        ),
    ]
