# Generated by Django 5.2 on 2025-04-06 03:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armazem', '0009_alter_estoque_quantidade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estoque',
            name='quantidade',
            field=models.DecimalField(decimal_places=3, default=0.0, help_text='Quantidade em Kg', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Quantidade (Kg)'),
        ),
        migrations.AlterField(
            model_name='estoqueindividual',
            name='quantidade',
            field=models.DecimalField(decimal_places=3, default=0.0, help_text='Quantidade em Kg', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Quantidade (Kg)'),
        ),
        migrations.AlterField(
            model_name='historicoestoque',
            name='peso',
            field=models.DecimalField(decimal_places=3, default=0.0, help_text='Peso em Kg', max_digits=10, verbose_name='Peso'),
        ),
    ]
