# Generated by Django 5.2 on 2025-05-06 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('armazem', '0010_alter_estoque_quantidade_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='preco',
        ),
    ]
