# Generated by Django 5.2 on 2025-04-05 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pessoa',
            new_name='Afiliado',
        ),
    ]
