# Generated by Django 5.2 on 2025-04-10 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('temperatura', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logs',
            options={'ordering': ['-data'], 'verbose_name': 'Log', 'verbose_name_plural': 'Logs'},
        ),
    ]
